 user:
  email:
    default: "nguyenduyson60@example.com"
    layout: "mailer"
    max_length: 255
  password:
    size: 6
  remember:
    value: "1"
  page:
    limit: 5
 micropost:
  content:
    length: 40
  image:
    size: 500
